---
url_package_release: http://repo.zabbix.com/zabbix/{{ zabbix_agent_major_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_major_version }}-1+{{ ansible_distribution_release }}_all.deb
# url_package_release: http://repo.zabbix.com/zabbix/{{ zabbix_agent_major_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_major_version }}-1+trusty_all.deb
